Only check previous version if one exists when running mdm release merge.
Summary: This makes it possible to merge initial releases.

Reviewers: O2 Material Motion, markwei

Reviewed By: O2 Material Motion, markwei

Tags: #material_motion

Differential Revision: http://codereview.cc/D1720

diff --git a/contributor_tools/release/release b/contributor_tools/release/release
--- a/contributor_tools/release/release
+++ b/contributor_tools/release/release
@@ -282,13 +282,15 @@ merge_release() {
 
   enforce_changelog_version
 
-  last_version=$(git describe --tags $(git rev-list --tags --max-count=1))
-  last_version=${last_version#v}
-  last_version=$(echo "$last_version" | sed "s:\.:\\\\.:g")
-  if grep -Ilr "$last_version" . | grep -v -f "$dir/versionignore"; then
-    echo "Old version $last_version found in the files above. Aborting release merge."
-    echo "Please run $parentcmd $cmd bump"
-    exit 1
+  if [ $(git rev-list --tags --max-count=1 2> /dev/null) ]; then
+    last_version=$(git describe --tags $(git rev-list --tags --max-count=1))
+    last_version=${last_version#v}
+    last_version=$(echo "$last_version" | sed "s:\.:\\\\.:g")
+    if grep -Ilr "$last_version" . | grep -v -f "$dir/versionignore"; then
+      echo "Old version $last_version found in the files above. Aborting release merge."
+      echo "Please run $parentcmd $cmd bump"
+      exit 1
+    fi
   fi
 
   echo "Merging release-candidate into stable and develop..."
