Add `mdm clone temp` command.
Summary:
`mdm clone temp` may be used to generate API diffs between two versions of a git repository.

Closes https://github.com/material-motion/material-motion-team/issues/99.

Reviewers: markwei, O2 Material Motion

Reviewed By: markwei, O2 Material Motion

Subscribers: markwei

Tags: #material_motion

Differential Revision: http://codereview.cc/D1336

diff --git a/contributor_tools/clone/clone b/contributor_tools/clone/clone
--- a/contributor_tools/clone/clone
+++ b/contributor_tools/clone/clone
@@ -47,8 +47,34 @@ clone_apple() {
   done
 }
 
+clone_tmp() {
+  if [[ -z "$1" ]]; then
+    usage
+    exit 1
+  fi
+
+  ref=$(git rev-list -n 1 "$1" -- 2> /dev/null || echo "")
+
+  if [ -z "$ref" ]; then
+    echo "$1 is not a known ref."
+    exit 1
+  fi
+
+  tmp_path=$(mktemp -d)
+  git_root="$(git rev-parse --show-toplevel | tail -n1)";
+
+  git clone "$git_root" "$tmp_path" -q || { echo "ERROR: Failed to clone."; exit 1; }
+  pushd "$tmp_path" >> /dev/null
+  git fetch -q || { echo "ERROR: Failed to update repo."; exit 1; }
+  git checkout "$ref" -q
+  popd >> /dev/null
+
+  echo "$tmp_path"
+}
+
 case "$1" in
   android)  clone_android ;;
   apple)    clone_apple ;;
+  temp|tmp) clone_tmp "${@:2}" ;;
   *)        usage ;;
 esac
